### ISSUE TITLE
when using .pug it is till trying to use .jade file

### ISSUE THREAD

**Issue by kenjilabs** [carloscuesta/generator-starterkit#11]
ENOENT: no such file or directory, open 'M:***_\**_**_\WebstormProjects\Scape\src\templates_includes_head.jade'
    at M:\**__\_*****\WebstormProjects\Scape\src\templates\index.pug line 3

**Comment by carloscuesta** [comment]
Thanks for reporting the bug @kenjilabs, fixed in 9000d8f
- [x] generator-starterkit@1.3.4 published.
