### ISSUE TITLE
Rewrite the generator using ES6

### ISSUE THREAD

**Issue by carloscuesta** [carloscuesta/generator-starterkit#15]
Rewrite the [main `index.js` file](https://github.com/carloscuesta/generator-starterkit/blob/master/generators/app/index.js) using ES6. :+1:

:star: [Writing Yeoman generators in ES6](http://mammal.io/articles/yeoman-generators-es6/)

**Comment by victoryforphil** [comment]
On it.

**Comment by Linko91** [comment]
WIP

**Comment by jlopezxs** [comment]
Done, PR: #17

**Comment by carloscuesta** [comment]
Fixed in #17!

Thanks @jlopezxs :tada:
